apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: "book-api"
  labels:
    app: "book-api"

spec:
  selector:
    matchLabels:
      app: "book-api"
  replicas: 8
  template:
    metadata:
      labels:
        app: "book-api"
    spec:
      containers:
        - name: "book-api"
          image: "motivado/hello-k8s:v5.2"
