# service semelhante a um load balancer

apiVersion: v1
kind: Service
metadata:
  name: "book-api-service"
spec:
  selector:
    app: "book-api"
  type: ClusterIP # ClusterIP, NodePort, LoadBalancer, ExternalName
  # CLusterIp é o tipo de service padrao, usado para comunicação interna entre os pods

  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
